#!/bin/sh
if [ -z "$${IPKG_INSTROOT}" ]; then
	( . /etc/uci-defaults/luci-shadowvpn ) && rm -f /etc/uci-defaults/luci-shadowvpn
	chmod 755 /etc/init.d/shadowvpn >/dev/null 2>&1
	/etc/init.d/shadowvpn enable >/dev/null 2>&1
fi
exit 0
