#!/bin/sh
if [ -z "$${IPKG_INSTROOT}" ]; then
	( . /etc/uci-defaults/luci-redsocks2 ) && rm -f /etc/uci-defaults/luci-redsocks2
	chmod 755 /etc/init.d/redsocks2 >/dev/null 2>&1
	/etc/init.d/redsocks2 enable >/dev/null 2>&1
fi
exit 0
